services:
  db:
    image: postgres:14
    container_name: workout_tracker_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./back-end/workoutDB-Setup.sql:/docker-entrypoint-initdb.d/workoutDB-Setup.sql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./back-end
    container_name: workout_tracker_backend
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 1h
    depends_on:
      - db
    ports:
      - "5001:5001"

  frontend:
    build:
      context: ./front-end
    container_name: workout_tracker_frontend
    restart: always
    environment:
      REACT_APP_API_URL: http://localhost:5001
    ports:
      - "3000:3000"

volumes:
  db_data:
